spring:
  data:
    neo4j:
      uri: "bolt://18.218.11.30:7687"
      username: "neo4j"
      password: "i-0fb5191d82a056e60"

logging:
  level:
    org:
      neo4j:
        ogm:
          drivers:
            bolt:
              request:
                BoltRequest: DEBUG